services:
  api:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - info_market_db
    restart: always
  info_market_db:
    container_name: info_market_db
    image: postgres:latest
    env_file:
      - .env
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
