services:
  api:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - db
    restart: always
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: pricewatch_user
      POSTGRES_PASSWORD: pricewatch_password
      POSTGRES_DB: pricewatch_db
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
